// 태그 표시 라벨. tags.generated.ts의 영문 식별자(snake_case)는 식별자/URL 파라미터로
// 그대로 사용하고, 사용자에게 보여줄 라벨만 여기서 현지화한다.
// 추후 다국어가 필요해지면 locale별 매핑(예: TAG_LABELS_EN)을 추가하면 된다.
//
// 영문 원문은 ALL_TAGS의 value 필드에 그대로 보존되어 있으니
// 이 파일을 지운다고 해서 식별자가 사라지지는 않는다.

const TAG_LABELS_KO: Record<string, string> = {
  math: '수학',
  implementation: '구현',
  dp: '다이나믹 프로그래밍',
  data_structures: '자료 구조',
  graphs: '그래프 이론',
  greedy: '그리디 알고리즘',
  string: '문자열',
  bruteforcing: '브루트포스 알고리즘',
  graph_traversal: '그래프 탐색',
  sorting: '정렬',
  ad_hoc: '애드 혹',
  geometry: '기하학',
  trees: '트리',
  number_theory: '정수론',
  segtree: '세그먼트 트리',
  binary_search: '이분 탐색',
  set: '집합과 맵',
  constructive: '해 구성하기',
  prefix_sum: '누적 합',
  arithmetic: '사칙연산',
  simulation: '시뮬레이션',
  combinatorics: '조합론',
  bfs: '너비 우선 탐색',
  case_work: '많은 조건 분기',
  bitmask: '비트마스킹',
  shortest_path: '최단 경로',
  dfs: '깊이 우선 탐색',
  hash_set: '해시를 사용한 집합과 맵',
  dijkstra: '데이크스트라',
  sweeping: '스위핑',
  disjoint_set: '분리 집합',
  backtracking: '백트래킹',
  dp_tree: '트리에서의 다이나믹 프로그래밍',
  priority_queue: '우선순위 큐',
  parsing: '파싱',
  tree_set: '트리를 사용한 집합과 맵',
  parametric_search: '매개 변수 탐색',
  game_theory: '게임 이론',
  divide_and_conquer: '분할 정복',
  probability: '확률론',
  stack: '스택',
  two_pointer: '두 포인터',
  dp_bitfield: '비트필드를 이용한 다이나믹 프로그래밍',
  lazyprop: '느리게 갱신되는 세그먼트 트리',
  primality_test: '소수 판정',
  flow: '최대 유량',
  offline_queries: '오프라인 쿼리',
  exponentiation_by_squaring: '분할 정복을 이용한 거듭제곱',
  knapsack: '배낭 문제',
  dag: '방향 비순환 그래프',
  coordinate_compression: '좌표 압축',
  recursion: '재귀',
  arbitrary_precision: '임의 정밀도 / 큰 수 연산',
  euclidean: '유클리드 호제법',
  grid_graph: '격자 그래프',
  topological_sorting: '위상 정렬',
  mst: '최소 스패닝 트리',
  precomputation: '오프라인 처리',
  linear_algebra: '선형대수학',
  convex_hull: '볼록 껍질',
  sieve: '에라토스테네스의 체',
  bipartite_matching: '이분 매칭',
  inclusion_and_exclusion: '포함 배제',
  lca: '최소 공통 조상',
  sparse_table: '희소 배열',
  parity: '패리티',
  traceback: '역추적',
  hashing: '해싱',
  randomization: '랜덤화',
  modular_multiplicative_inverse: '모듈로 곱셈 역원',
  floyd_warshall: '플로이드–워셜',
  scc: '강한 연결 요소',
  smaller_to_larger: '작은 집합에서 큰 집합으로 합치기',
  line_intersection: '선분 교차 판정',
  sqrt_decomposition: '제곱근 분할법',
  fft: '고속 푸리에 변환',
  calculus: '미적분학',
  trie: '트라이',
  deque: '덱',
  prime_factorization: '소인수분해',
  geometry_3d: '3차원 기하학',
  heuristics: '휴리스틱',
  ternary_search: '삼분 탐색',
  euler_tour_technique: '오일러 경로 테크닉',
  sliding_window: '슬라이딩 윈도우',
  suffix_array: '접미사 배열과 LCP 배열',
  mcmf: '최소 비용 최대 유량',
  cht: '볼록 껍질을 이용한 최적화',
  sprague_grundy: '스프라그–그런디',
  difference_array: '차분 배열',
  mitm: '중간에서 만나기',
  pythagoras: '피타고라스 정리',
  lis: '가장 긴 증가하는 부분 수열',
  centroid: '센트로이드',
  permutation_cycle_decomposition: '순열 사이클 분할',
  bitset: '비트셋',
  linearity_of_expectation: '기댓값의 선형성',
  kmp: 'KMP',
  gaussian_elimination: '가우스 소거법',
  bipartite_graph: '이분 그래프',
  hld: 'Heavy–Light 분할',
  mfmc: '최대 유량 / 최소 컷',
  polygon_area: '다각형의 넓이',
  centroid_decomposition: '센트로이드 분할',
  physics: '물리학',
  eulerian_path: '오일러 경로',
  flt: '페르마의 소정리',
  '0_1_bfs': '0-1 너비 우선 탐색',
  flood_fill: '플러드 필',
  articulation: '단절점과 단절선',
  queue: '큐',
  pigeonhole_principle: '비둘기집 원리',
  functional_graph: '함수형 그래프',
  '2_sat': '2-SAT',
  tsp: '외판원 순회 문제',
  deque_trick: '덱을 이용한 트릭',
  rerooting: '리루팅 (Rerooting)',
  pst: '퍼시스턴트 세그먼트 트리',
  dp_digit: '자릿수 다이나믹 프로그래밍',
  planar_graph: '평면 그래프',
  point_in_convex_polygon: '볼록 다각형 내부의 점 판정',
  bcc: '이중 연결 요소',
  generating_function: '생성 함수',
  harmonic_number: '조화수',
  euler_phi: '오일러 피 함수',
  angle_sorting: '각도 정렬',
  linked_list: '연결 리스트',
  crt: '중국인의 나머지 정리',
  invariant: '불변량',
  tree_diameter: '트리의 지름',
  mo: "Mo's 알고리즘",
  maximum_subarray: '최대 부분 배열',
  cactus: '선인장',
  bellman_ford: '벨만–포드',
  divide_and_conquer_optimization: '분할 정복을 사용한 최적화',
  extended_euclidean: '확장 유클리드 호제법',
  splay_tree: '스플레이 트리',
  dp_sum_over_subsets: '부분 집합의 합 다이나믹 프로그래밍',
  half_plane_intersection: '반평면 교집합',
  pbs: '병렬 이분 탐색',
  euler_characteristic: '오일러 지표',
  rotating_calipers: '회전하는 캘리퍼스',
  regex: '정규 표현식',
  multi_segtree: '다차원 세그먼트 트리',
  pollard_rho: '폴라드 로',
  lcs: '최장 공통 부분 수열',
  slope_trick: '기울기 트릭',
  manacher: '매내처 알고리즘',
  aho_corasick: '아호-코라식',
  miller_rabin: '밀러–라빈 소수 판별법',
  dp_deque: '덱을 이용한 다이나믹 프로그래밍',
  tree_isomorphism: '트리 동형 사상',
  mobius_inversion: '뫼비우스 반전',
  point_in_non_convex_polygon: '다각형 내부의 점 판정',
  merge_sort_tree: '머지 소트 트리',
  cartesian_tree: '카르테시안 트리',
  numerical_analysis: '수치해석',
  link_cut_tree: '링크/컷 트리',
  simulated_annealing: '시뮬레이티드 어닐링',
  dp_connection_profile: '연결 프로파일을 이용한 다이나믹 프로그래밍',
  rabin_karp: '라빈–카프',
  statistics: '통계학',
  li_chao_tree: '리-차오 트리',
  berlekamp_massey: '벌래캠프–매시',
  hall: '홀의 결혼 정리',
  xor_basis: 'XOR 기저',
  geometric_boolean_operations: '기하학적 불리언 연산',
  alien: 'Alien Trick',
  offline_dynamic_connectivity: '오프라인 동적 연결성 판정',
  z: 'Z',
  tree_compression: '트리 압축',
  hungarian: '헝가리안',
  linear_programming: '선형 계획법',
  lucas: '뤼카 정리',
  beats: '세그먼트 트리 비츠',
  duality: '쌍대성',
  circulation: '서큘레이션',
  voronoi: '보로노이 다이어그램',
  polynomial_interpolation: '다항식 보간법',
  dual_graph: '쌍대 그래프',
  green: '그린 정리',
  min_enclosing_circle: '최소 외접원',
  bulldozer: '불도저 트릭',
  monotone_queue_optimization: '단조 큐를 사용한 최적화',
  discrete_log: '이산 로그',
  kitamasa: '키타마사',
  cdq: 'CDQ',
  general_matching: '일반 매칭',
  pick: '픽의 정리',
  geometry_hyper: '초기하학',
  suffix_tree: '접미사 트리',
  dominator_tree: '도미네이터 트리',
  matroid: '매트로이드',
  differential_cryptanalysis: '차분 공격',
  utf8: '유니코드 문자열 처리',
  degree_sequence: '차수열',
  burnside: '번사이드 보조정리',
  tree_decomposition: '트리 분할',
  top_tree: '톱 트리',
  bidirectional_search: '양방향 탐색',
  pisano: '피사노 주기',
  rope: '로프',
  gradient_descent: '경사 하강법',
  dial: "Dial's 알고리즘",
  palindrome_tree: '회문 트리',
  discrete_sqrt: '이산 제곱근',
  lgv: 'LGV 보조정리',
  knuth_x: "Knuth's X",
  dancing_links: '댄싱 링크',
  floor_sum: '바닥 함수의 합',
  kinetic_segtree: '키네틱 세그먼트 트리',
  bayes: '베이즈 정리',
  delaunay: '들로네 삼각분할',
  stable_marriage: '안정 결혼 문제',
  knuth: '크누스 최적화',
  bitset_lcs: '비트셋을 이용한 LCS',
  birthday: '생일 문제',
  hirschberg: '히르쉬베르크',
  chordal_graph: '코달 그래프',
  multipoint_evaluation: '다항식의 다중 점 계산',
  lte: 'Lifting The Exponent',
  directed_mst: '방향 최소 스패닝 트리',
  stoer_wagner: '슈토어–바그너',
  hackenbush: '헤켄부시 게임',
  majority_vote: '보이어–무어 다수결 투표',
  rb_tree: '레드–블랙 트리',
}

/** 태그 식별자(snake_case 영문)를 사용자 표시용 라벨로 변환한다.
 *  매핑이 없으면 원문 식별자를 그대로 반환한다 — 이 경우 tag-labels.ts에
 *  새 항목을 추가할 필요가 있다는 신호다. */
export function getTagLabel(value: string): string {
  return TAG_LABELS_KO[value] ?? value
}
